spring:
  application:
    name: @project.artifactId@
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/trend?autoReconnect=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: admin
    type: com.alibaba.druid.pool.xa.DruidXADataSource
    max-active: 5
    min-idle: 1
    initial-size: 1
    test-on-borrow: true
    test-on-return: true
    test-while-idle: true
    validation-query: select 1
    #每10分钟收集空闲连接，单位毫秒#
    time-between-eviction-runs-millis: 600000
    #连接的最大空闲时间，单位毫秒，60分钟
    min-evictable-idle-time-millis: 3600000
    max-wait: 30000
    jdbc-interceptors: ConnectionState;SlowQueryReport(threshold=0)
  jta:
    enabled: true
    log-dir: trendLog/jtalog
    atomikos:
      datasource:
        default-isolation-level: READ COMMITTED
      properties:
        console-log-level: DEBUG
        output-dir: trend/jtalog
        log-base-dir: trend/jtalog
        log-base-name: atomikos-transaction
logging:
  path: trendLog/
  level:
    xyz.liinns: DEBUG
    root: INFO
