spring:
  profiles:
    active: dev
  # Application
  application:
    name: @project.artifactId@
  # DataSource
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/trend?autoReconnect=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: admin
    type: com.alibaba.druid.pool.xa.DruidXADataSource
    max-active: 5
    min-idle: 1
    initial-size: 1
    test-on-borrow: true
    test-on-return: true
    test-while-idle: true
    validation-query: select 1
    #每10分钟收集空闲连接，单位毫秒#
    time-between-eviction-runs-millis: 600000
    #连接的最大空闲时间，单位毫秒，60分钟
    min-evictable-idle-time-millis: 3600000
    max-wait: 30000
    jdbc-interceptors: ConnectionState;SlowQueryReport(threshold=0)
  # JTA
  jta:
    enabled: true
    log-dir: ./trendLog/jtalog
    atomikos:
      datasource:
        default-isolation-level: READ COMMITTED
      properties:
        console-log-level: DEBUG
        output-dir: ./trendLog/jtalog
        log-base-dir: ./trendLog/jtalog/
        log-base-name: atomikos-transaction
  # Elasticsearch
  data:
    elasticsearch:
      #cluster-name: elasticsearch
      #cluster-nodes: localhost:9300
      properties:
        path:
          logs: ./trendLog/elasticsearch/log/
          data: ./data
    mongodb:
      host: localhost
      port: 27017
  # Mail
  #mail:
  #  default-encoding: UTF-8
  #  host: smtp.quyiyuan.com
  #  username: insurance@quyiyuan.com
  #  password: Abcd@1234
  # Thymeleaf
  #thymeleaf:
# Logging
logging:
  path: ./trendLog
  level:
    xyz.liinns: DEBUG
    root: INFO
# Flyway flyway.[url,user,password]
# read more... http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-use-a-higher-level-database-migration-tool
flyway:
  locations: migration, ${spring.profiles.active}/migration
server:
  port: 8080